import './globals.css'
import ReduxProvider from '@/redux/provider'
import ToastWrapper from '@/components/Toast/ToastWrapper'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'LeetCode',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ToastWrapper>{children}</ToastWrapper>
        </ReduxProvider>
      </body>
    </html>
  )
}
